[features]
seeds = false
skip-lint = false
[programs.testnet]
solana_spltoken_staking = "A8euEuZ3kkhtwnhf7tHqXyst7AigA8pneC12mNPjRNry"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "~/Downloads/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
