[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_spltoken_vesting = "FPMWFeVjrYcZJXRDU8W2XrMVNHmHGa6qXrJ16rW92fRp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/afolabi/Downloads/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
