[features]
seeds = false
skip-lint = false
[programs.testnet]
z01zet_tokenomics_contract = "EBdu7ax329bQdrSqzfUhzPbZm74vQbL3RGiYHqoQ4pku"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "/home/afolabi/Downloads/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
